### ISSUE TITLE
about extract_roi

### ISSUE THREAD

**Issue by zz10001** [JunMa11/PrePostSeg#1]
Hi,
If i use simpleitk replace nibabel, I can use the same find_bb as follows `img_data[bb[0]:bb[1], bb[2]:bb[3], bb[4]:bb[5]]`, Is it right?

**Comment by JunMa11** [comment]
Hi @zz10001 ,

Thanks for your interest. 
Sorry, i'm not sure.
It seems `simpleitk` has a different coordinate system from `nibabel`.
You can save your results and check whether it is right.

**Comment by zz10001** [comment]
Thanks for your quick reply, I will have a try. Thanks you!
